Feature UNO 467 - Extend Response Properties on text Entry interaction with possibility to set baseType property
oat-sa/extension-tao-itemqti pull request #1519
Opened 2020-08-27 11:13 UTC by habemuscode

**Needs to be merged and publish before this PR**

https://github.com/oat-sa/tao-item-runner-qti-fe/pull/96

**Related to**

https://oat-sa.atlassian.net/browse/UNO-467

**Description**

**As** content creator
**I would** like during the assessment on textEntry interaction and in case of touch-based devices, to open the numeric keyboard for input
**so that**  we increase user experience and eliminate possibilities for wrong input

**Acceptance Criteria**

**AC1**

**GIVEN** an inline `textEntry` interaction flagged as expecting a numeric input
**WHEN** the test taker tap on the input field with a touch-based device like a tablet
**THEN** the device opens the numeric keyboard instead of the alphanumeric keyboard

**Considerations**

The main goal is to implement this story on the NextGen test runner.

- NextGen test runner

Implementation of NextGen test runner already support such behavior.  We have to add inputmode=numeric if the `baseType` is integer and `inputmode=decimal` if the `baseType` is a `float`

- CurrentGen test runner

Implementation for CurrentGen test runner implement similar logic as on NextGen test runner relying on `inputmode`

**How to Test**

**Requires touch-based device, tablet or similar**

Create an item with `textEntry` interaction with Response `baseType` declaration set to integer or float.

Create a test including the item(s) created before and publish to NextGen to deliver an environment that is linked with New Test runner ex.

on demo.udir publish on using tenant: UDIR QA (new Test Runner)

Launch delivery execution from the touch-based device

Verify during input on textEntry interaction with numeric `baseType`,  numeric keyboard is rendered.

2020-08-27 16:03 UTC, adriloma commented
Seems that some Jenkins job is failing.

2020-08-28 06:37 UTC, andrey-ponamarev requested changes
Please update package lock file

2020-08-28 07:16 UTC, habemuscode commented
@andrey-ponamarev  @adriloma This PR needs the other merge before (check description). I just created to be more fast merging, instead of add people after first was merge. I can get approvals before as long as is just version update

2020-08-28 07:33 UTC, bziondik approved these changes
Add lock file
- [ ]  New code is covered by tests (if applicable)
- [x]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [ ]  New code is not subject to concurrency issues (if applicable)
- [x]  Feature is working correctly on my local machine (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request title and description are meaningful

2020-08-28 11:40 UTC, habemuscode commented
@andrey-ponamarev Lock file pushed

2020-08-28 11:44 UTC, jsconan approved these changes
Code review only.

**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

2020-08-28 11:47 UTC, merged