[TAO-10497] R&O Processing - Refactor qti item loader
oat-sa/extension-tao-itemqti pull request #1527
Opened 2020-09-07 07:44 UTC by atsymuk

Related to : https://oat-sa.atlassian.net/browse/TAO-10497
 
Update package.json

#### How to test
 
- prepare an instance of TAO with `xmlEdit` and `xmlEditRp ` installed
- prepare an item with interactions with different response processing templates
- try to open item for authoring. make sure that response processing templates properly recognized
- prepare an item with custom response processing
- try to open item from authoring. make sure that response processing templates properly recognized
- prepare a delivery
- execute delivery as test taker
- check that test items loaded correctly
  
#### Dependencies
   
Companion PR :
 - [ ] https://github.com/oat-sa/tao-item-runner-qti-fe/pull/104

2020-09-14 11:41 UTC, jsconan requested changes
There are failing unit tests in `taoQtiItem/views/js/test/qtiXmlRenderer/test.html`

2020-09-16 06:29 UTC, atsymuk commented
> There are failing unit tests in `taoQtiItem/views/js/test/qtiXmlRenderer/test.html`

i did not take into consideration feedback response rules. fixed in this commit https://github.com/oat-sa/tao-item-runner-qti-fe/pull/104/commits/3d2e72b5a61a2558c4acf25c335f3f81797609ce

2020-09-16 07:40 UTC, jsconan approved these changes
**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`

2020-09-18 10:19 UTC, lecosson approved these changes

2020-09-18 10:22 UTC, merged