Fix/tao 9843/media interaction playback continues after leaving page
oat-sa/extension-tao-itemqti pull request #1530
Opened 2020-09-09 15:26 UTC by AndreyNegrov

**Related to task:**  https://oat-sa.atlassian.net/browse/TAO-9843
**Description:** Media interaction: playback continues after leaving page if autostart is set
**How to test:** 
- Create an item with Media interaction
- Upload audio/video file
- Set 'Autostart' in the Interaction Properties
- Save and Preview

**Expected result:** playback autostarted in authoring mode finishes as soon as Preview mode is opened.

2020-09-10 07:14 UTC, andrey-ponamarev approved these changes
⚠️ The issue still exist when user is opening preview mode and interaction is "in active" state.

- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [x] The feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request's target is not `master`

2020-09-14 08:57 UTC, zagovorichev requested changes
There is an issue in the behavior: on the second or third preview action, it doesn't pause the video

2020-09-14 08:57 UTC, zagovorichev commented on views/js/qtiCreator/renderers/interactions/MediaInteraction.js
> +            interaction.mediaElement.execute('pause');
I would use `stop` instead

2020-09-14 11:36 UTC, AndreyNegrov commented on views/js/qtiCreator/renderers/interactions/MediaInteraction.js
> +            interaction.mediaElement.execute('pause');
fixed

2020-09-14 11:37 UTC, AndreyNegrov commented
> There is an issue in the behavior: on the second or third preview action, it doesn't pause the video

fixed

2020-09-14 12:14 UTC, habemuscode commented
Merge develop and bump manifest again

2020-09-14 12:49 UTC, habemuscode approved these changes
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [x] The feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request's target is not `master`

2020-09-14 12:52 UTC, merged