Fix/uno 579/item error message hidden
oat-sa/extension-tao-itemqti pull request #1534
Opened 2020-09-11 13:04 UTC by AndreyNegrov

2020-09-11 13:27 UTC, habemuscode approved these changes
- [ ]  New code is covered by tests (if applicable)
- [ ]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [ ]  New code is not subject to concurrency issues (if applicable)
- [x]  Feature is working correctly on my local machine (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request title and description are meaningful

2020-09-14 07:20 UTC, zagovorichev requested changes
z-index should be fixed to not cover other popup windows

2020-09-14 10:14 UTC, AndreyNegrov commented
> z-index should be fixed to not cover other popup windows

fixed

2020-09-14 11:05 UTC, zagovorichev requested changes

2020-09-14 11:05 UTC, zagovorichev commented on views/js/qtiCreator/tpl/notifications/invalidInfoBox.tpl
> +<div class="feedback-warning-popup" data-widget-component="{{serial}}">
not sure that this a good idea: this box could be used by other interactions or anything in the qtiCreator context, could you do not change classes, you could access this.$messageBox and add there your own class declaration

2020-09-14 11:08 UTC, zagovorichev commented on views/js/qtiCreator/tpl/notifications/invalidInfoBox.tpl
> +<div class="feedback-warning-popup" data-widget-component="{{serial}}">
understood, you changed all states component, I will check it again

2020-09-15 11:46 UTC, zagovorichev commented
I had a conversation with UI/UX (Sam) and changed this solution little bit, in this PR: https://github.com/oat-sa/extension-tao-itemqti/pull/1536

2020-09-15 11:46 UTC, closed without merging