Fix/tao 10258/label text added right after putting custom interactions canvas cleared
oat-sa/extension-tao-itemqti pull request #1550
Opened 2020-09-25 13:42 UTC by AndreyNegrov

**Related to task:**  https://oat-sa.atlassian.net/browse/TAO-10258
**Description:** Label text added right after putting the Custom Interactions to canvas is cleared
**How to test:** 
1. Create new test item, click Authoring.
2. Expand Custom Interactions section at left, drag and drop Math entry/Audio/Likert Scale interaction to canvas
3. Click "some text..." label and enter description text
4. Click out of the interaction on canvas/Click "Save" and "Preview" buttons/Click "Done" button
5. Observe the label
**Expected Result:**
The entered text is displayed in field with "some text..." label

2020-09-25 15:11 UTC, andrey-ponamarev approved these changes
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [x] The feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request's target is not `master`

2020-09-29 13:38 UTC, zagovorichev requested changes

2020-09-29 13:38 UTC, zagovorichev commented on views/js/portableLib/OAT/util/html.js
> -            //remove xml ns (would break jquery selector otherwise)
I'm wondering what does it mean, have you asked Sam or someone who could be aware of that?

2020-09-29 13:38 UTC, zagovorichev commented on views/js/portableLib/OAT/util/html.js
> -            markup = xml.removeNamespace(markup);
If you don't use `xml` anymore, could you remove 'taoQtiItem/portableLib/OAT/util/xml', please?

2021-03-30 14:28 UTC, closed without merging