Fix/CGA-167/Don't determinate interaction wrapper as a text block
oat-sa/extension-tao-itemqti pull request #1556
Opened 2020-10-01 12:28 UTC by andrey-ponamarev

**Related to task:**  https://oat-sa.atlassian.net/browse/CGA-167
**Description:** The COGNIA client has some items where interactions are wrap to the `div`'s element without the `grid` layout. In this case the element is determining as a text block and will not work properly in editing state.
**How to test:** 
- The taoMp extensions must be installed to support scaffolding PCI
- Download the item attached to the https://oat-sa.atlassian.net/browse/CGA-167
- In editing mode user should be able to make changes to the item by using editor

2020-10-01 12:45 UTC, jsconan requested changes
It works fine.
However:
- Regarding the code, there are several calls to `console.log()`. It looks like a debug session was not cleaned up :)
- And unfortunately, the unit tests are failing.

2020-10-01 12:45 UTC, jsconan commented on views/js/qtiCreator/widgets/item/Widget.js
> +            console.log('PUSH SUBCONTAINERS');
Forgotten debug line?

2020-10-01 13:17 UTC, bziondik approved these changes
Code review only
- [ ]  New code is covered by tests (if applicable)
- [ ]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [x]  New code is not subject to concurrency issues (if applicable)
- [ ]  Feature is working correctly on my local machine (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request title and description are meaningful

2020-10-01 15:35 UTC, jsconan requested changes
Unfortunately, unit tests are still failing

2020-10-02 11:16 UTC, andrey-ponamarev commented
> Unfortunately, unit tests are still failing

@jsconan we have the unit test error on the `develop` branch as well 😔
By running `grunt testall` command is not visible, but by using `grunt connect:test:keepalive --testPort=1234` it's not breaking unit tests but it's visible in console
<img width="1792" alt="Screenshot 2020-10-02 at 13 13 09" src="https://user-images.githubusercontent.com/6339002/94917587-13a16980-04b1-11eb-813b-1fa4bfe1a2bd.png">

The problem somehow became visible after my code changes. So for now I've increased the timeout to give `ckEditor` more time to initialized

2020-10-02 13:52 UTC, jsconan approved these changes
**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`

2020-10-05 08:44 UTC, merged