Feature/nex 2059/svgz support
oat-sa/extension-tao-itemqti pull request #1557
Opened 2020-10-01 15:09 UTC by boajer

https://oat-sa.atlassian.net/browse/NEX-2059

TODO
- [ ] Unit test

2020-10-02 14:03 UTC, bartlomiejmarszal reviewed
- [ ] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful

2020-10-02 14:04 UTC, bartlomiejmarszal approved these changes
Tested on local machine

2020-10-05 07:40 UTC, gabrielfs7 commented on model/compile/QtiAssetCompiler/QtiItemAssetCompiler.php
> +        return $packedAsset->getMediaAsset()->getMediaSource()->getBaseName($link);
Is it covered in the test? I remember this was a critical part changed before and we had some issues. If possible would be nice to have a test for this.

2020-10-05 07:40 UTC, gabrielfs7 reviewed
Can we add tests?

- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

2020-10-05 11:54 UTC, mike-ionut-mihai-sandu-tao requested changes
conflict

2020-10-05 12:35 UTC, siwane approved these changes
- [ ] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful

2020-10-05 15:26 UTC, mike-ionut-mihai-sandu-tao approved these changes
- [x] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

2020-10-05 15:27 UTC, merged