Fix/NSA-147/action button accessibility at the bottom of sidebars
oat-sa/extension-tao-itemqti pull request #1562
Opened 2020-10-13 07:02 UTC by andrey-ponamarev

**Related to task:**  https://oat-sa.atlassian.net/browse/NSA-147
**Description:**  Add space at the bottom of sidebars to prevent overlapping sidebars action buttons with footer.

<img width="1126" alt="Screenshot 2020-10-08 at 15 20 06" src="https://user-images.githubusercontent.com/6339002/95465634-ae9bb700-097b-11eb-83be-fd4edc54f3fe.png">

**Steps to reproduce:**
1. Login as admin
2. Change the browser size to have a few rows in the header 
2. Go to Items tab
3. Create a new item and go to Authoring
4. Add any interaction to the canvas (f.e. choice) and go to response mode
5. Click "Add an outcome" button until it reaches the bottom of the sidebar

Actual result: "Add an outcome" button is not accessible

2020-10-13 07:14 UTC, jsconan reviewed
I was unable to reproduce the issue, but the code looks ok, at least it doesn't seem to harm.

Just one remark: can you compile the SCSS and add the bundled css files?
`cd tao/views/build && npx grunt taoqtiitemsass`

**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`

2020-10-13 19:02 UTC, bziondik reviewed
- [ ]  New code is covered by tests (if applicable)
- [x]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [x]  New code is not subject to concurrency issues (if applicable)
- [x]  Feature is working correctly on my local machine (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request title and description are meaningful

2020-10-13 19:02 UTC, bziondik requested changes
Please, add `css` files

2020-10-19 11:17 UTC, btamas approved these changes

2020-10-22 14:19 UTC, merged