[Feature] CON 81 - Enable text wrap passages
oat-sa/extension-tao-itemqti pull request #1580
Opened 2020-11-11 14:18 UTC by habemuscode

**Related to this issue**

https://oat-sa.atlassian.net/browse/CON-81

**Story**

As the author, I want to be able to wrap my text around pictures, so that I can produce passages that look like real-life media content.

Currently, I am only able to anchor images AS a character. In order for the text to be able to flow around it, I will need to be able to anchor it TO a character and specify how text is supposed to wrap around it

Required wrap modes:

- Float off
- Float right
- Float left

**Acceptance Criteria**

- Anchoring an image as a character should still be possible
- Text wrapping should not be available when the image is anchored as a character
- Images maintain position within their paragraph when text is added before or after
- Responsive images are still supported if the image is anchored to a character
- Exported items will contain the relevant CSS to ensure the rendering will be correct in any environment
- Exporting and reimporting an item will maintain the anchoring and wrapping

2020-12-15 15:34 UTC, pnal approved these changes
Nothing suspicious, LGTM
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful

2020-12-15 15:53 UTC, gabrielfs7 approved these changes
Code LGTM 

- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

2020-12-16 10:55 UTC, bziondik requested changes
Update version

2020-12-16 17:13 UTC, mike-ionut-mihai-sandu-tao requested changes
manifest cage required

2020-12-17 08:44 UTC, habemuscode commented
@bziondik  @mike-ionut-mihai-sandu-tao Manifest pushed

2020-12-17 08:49 UTC, shpran approved these changes
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

2020-12-17 13:25 UTC, bziondik approved these changes
- [ ]  New code is covered by tests (if applicable)
- [ ]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [x]  New code is not subject to concurrency issues (if applicable)
- [ ]  Feature is working correctly on my local machine (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request title and description are meaningful

2021-02-25 21:07 UTC, gabrielfs7 commented
We need to check the build, probably missing some composer.json dependencies

2021-02-26 13:09 UTC, bziondik commented on views/js/qtiCreator/widgets/static/helpers/inline.js
> +            $container.removeClass('rgt txt-rgt lft txt-lft');
Do we need this? in Item Authoring we don't have option Position for images

2021-05-20 05:53 UTC, 404passionFruit approved these changes
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

2021-06-03 06:37 UTC, 404passionFruit commented
Converted to draft as there is an alternative solution https://github.com/oat-sa/extension-tao-itemqti/pull/1761

2021-06-03 08:43 UTC, habemuscode commented
Closed in favor of https://github.com/oat-sa/extension-tao-itemqti/pull/1761

2021-06-03 08:43 UTC, closed without merging