Fix/ms 579/highlighter support in text entry inline interaction
oat-sa/extension-tao-itemqti pull request #1586
Opened 2020-11-19 17:23 UTC by AnastasiaArcadia

Related to: https://oat-sa.atlassian.net/browse/MS-579

**Changes**

In text entry inline interactions `input` element was changed to `div` for `reviewRenderer` to support highlight plugin.

**How to test?**

- Create a test with text entry inline interaction
- Take the test on tao
- Login as a scorer on MS to review the responses
- All the text entry inline interactions should be displayed as expected and should have been rendered in a `div` instead of `input`

2020-11-25 09:18 UTC, andrey-ponamarev commented on views/package.json
> +        "@oat-sa/tao-item-runner-qti": "git://github.com/oat-sa/tao-item-runner-qti-fe.git#fix/MS-579/highlighter-support-in-text-entry-inline-interaction"
- [ ]  Please, don't forget to change the version

2020-11-25 09:19 UTC, andrey-ponamarev approved these changes
- [x] ⚠️ Required changes in package*.json
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [ ] The feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request's target is not `master`

2020-11-30 15:05 UTC, ampaveliev approved these changes
Code review only. Looks fine

2020-12-11 09:11 UTC, andrey-ponamarev requested changes
Please fix conflicts and update version in package*.json

2020-12-11 11:01 UTC, andrey-ponamarev approved these changes
- [x] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [x] The feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request's target is not `master`

2020-12-11 11:08 UTC, merged