update item runner
oat-sa/extension-tao-itemqti pull request #1593
Opened 2020-12-03 07:07 UTC by anshul119

Ticket: https://oat-sa.atlassian.net/browse/MS-532

### What has changed?

- Item runner is updated

### Requires

https://github.com/oat-sa/tao-item-runner-qti-fe/pull/125/

### Tasks

- [ ] Change package version according to this after release: https://github.com/oat-sa/tao-item-runner-qti-fe/pull/125/

2020-12-03 07:52 UTC, ampaveliev requested changes
Don't forget to update the manifest file

2020-12-08 11:33 UTC, AnastasiaArcadia approved these changes
- [x] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [x] The feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request's target is not `master`

2020-12-08 14:24 UTC, andrey-ponamarev approved these changes
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [ ] The feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request's target is not `master`

2020-12-08 14:25 UTC, ampaveliev approved these changes

2020-12-09 15:07 UTC, merged