feat: if preselected empty we are using default list
oat-sa/extension-tao-itemqti pull request #1654
Opened 2021-03-05 14:43 UTC by bartlomiejmarszal

Providing user with preselected default list mime types for upload interaction.

https://oat-sa.atlassian.net/browse/AUT-19

2021-03-08 08:39 UTC, mike-ionut-mihai-sandu-tao commented on views/js/qtiCreator/widgets/interactions/uploadInteraction/states/Question.js
> +        const config = module.config();
i think you need to run 
```
npx prettier --write and the location of this file
npx prettier --check
npm eslint
```

2021-03-09 08:07 UTC, bziondik requested changes

2021-03-09 08:07 UTC, bziondik commented on views/js/qtiCreator/widgets/interactions/uploadInteraction/states/Question.js
> +        if (preselected.length === 0 && config.defaultList.length > 0) {
```suggestion
        if (preselected.length === 0 && config.defaultList && config.defaultList.length > 0) {
```

2021-03-09 08:07 UTC, bziondik commented on views/js/qtiCreator/widgets/interactions/uploadInteraction/states/Question.js
> +            preselected = preselected.concat(config.defaultList)
```suggestion
            preselected = preselected.concat(config.defaultList);
```

2021-03-09 12:45 UTC, bziondik approved these changes
- [ ]  New code is covered by tests (if applicable)
- [x]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [x]  New code is not subject to concurrency issues (if applicable)
- [x]  Feature is working correctly on my local machine (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request title and description are meaningful

2021-03-10 07:58 UTC, mike-ionut-mihai-sandu-tao approved these changes
- [ ] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful

2021-03-10 09:28 UTC, AnastasiaArcadia approved these changes
- [ ]  New code is covered by tests (if applicable)
- [x]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [x]  New code is not subject to concurrency issues (if applicable)
- [ ]  Feature is working correctly on my local machine (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request title and description are meaningful

2021-03-26 08:54 UTC, merged