Feature/adf 89/tabular import integration branch
oat-sa/extension-tao-itemqti pull request #1695
Opened 2021-04-14 08:11 UTC by boajer

2021-05-14 08:42 UTC, ktsirkou commented on templates/import/item_match_correct_response.xml.tpl
> +    <responseProcessing>
Why not use the template directly http://www.imsglobal.org/question/qtiv2p2/rptemplates/match_correct.xml
Also the outcome variable SCORE_RESPONSE seems redundant.

2021-05-18 07:56 UTC, gabrielfs7 requested changes
We cannot forget to

- [x] Fix all broken tests
- [ ] Update composer.json if required 
- [ ] Cover all TODOs in the list if are blocker

2021-05-18 14:44 UTC, AntonNeviarouski commented
QA verified on http://tabular-adf-156-items-import.playground.kitchen.it.taocloud.org:46001/

2021-05-18 14:59 UTC, gabrielfs7 approved these changes
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

2021-05-18 15:11 UTC, merged