fix: remove upperbound value if max field is 0
oat-sa/extension-tao-itemqti pull request #1796
Opened 2021-06-28 10:53 UTC by Silvia-loza

2021-07-01 09:10 UTC, bziondik approved these changes
- [ ]  New code is covered by tests (if applicable)
- [x]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [x]  New code is not subject to concurrency issues (if applicable)
- [x]  Feature is working correctly on my local machine (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request title and description are meaningful

2021-07-01 09:54 UTC, AnastasiaArcadia requested changes
Unfortunately, this affects another interactions. For example for the Associate Interaction I'm getting an error now:
<img width="904" alt="Снимок экрана 2021-07-01 в 12 52 15" src="https://user-images.githubusercontent.com/60703274/124104906-65404a00-da6b-11eb-9f24-8a122dacc817.png">

2021-07-01 14:15 UTC, Silvia-loza commented on views/js/qtiCreator/widgets/helpers/formElement.js
> +                    //if a null attribute is not allowed, should be removed.
All this part has been removed at the end.

2021-07-02 11:10 UTC, AnastasiaArcadia approved these changes
- [ ]  New code is covered by tests (if applicable)
- [x]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [x]  New code is not subject to concurrency issues (if applicable)
- [x]  Feature is working correctly on my local machine (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request title and description are meaningful

2021-07-05 07:03 UTC, AntonNeviarouski commented
QA verified on http://test-silvia.playground.kitchen.it.taocloud.org:41441/

2021-07-05 10:09 UTC, merged