Feature/tr 894 rtl for order list
oat-sa/extension-tao-itemqti pull request #1871
Opened 2021-09-02 16:37 UTC by meefox

Related to https://oat-sa.atlassian.net/browse/TR-894

2021-09-03 07:01 UTC, marpesia requested changes
It could be great to have some info about the changes and How to test them in the PR description box.
Besides a composer.json file, I've seen yours is different from mine.

2021-09-03 08:40 UTC, meefox commented on views/scss/qti/_qti-base.scss
> +            // padding-right: 3px;
oh may, thanks

2021-09-03 09:19 UTC, meefox commented
> It could be great to have some info about the changes and How to test them in the PR description box.
> Besides a composer.json file, I've seen yours is different from mine.

yes, it is one the way :) coming together with test env.

2021-09-07 11:52 UTC, marpesia approved these changes
**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [x] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ]  Commits messages are meaningful
- [ ]  Commits are atomic
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

2021-09-07 13:37 UTC, jsconan requested changes
The code looks ok.
However, there is an issue when mixing RTL layout with LTR item: the LTR item is displayed in RTL.
![image](https://user-images.githubusercontent.com/1500098/132354143-21b78a41-c54d-4127-9175-815903922127.png)

2021-09-07 17:35 UTC, meefox commented
> The code looks ok.
> However, there is an issue when mixing RTL layout with LTR item: the LTR item is displayed in RTL.
> ![image](https://user-images.githubusercontent.com/1500098/132354143-21b78a41-c54d-4127-9175-815903922127.png)

Added rule to be dependant on item's level dir RTL/LTR.
This kind of problem will persist till we add an item level `dir= LTR` to override `dir=RTL` from `body` in order to set DOM to LTR direction.

2021-09-08 10:01 UTC, jsconan approved these changes
It works well, together with #1814 which is a prerequisite.

**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [x] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] Commits messages are meaningful
- [x] Commits are atomic
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

2021-09-10 14:39 UTC, merged