fix: id attributes get translated
oat-sa/extension-tao-itemqti pull request #1899
Opened 2021-09-28 10:41 UTC by Silvia-loza

Related Issue: https://oat-sa.atlassian.net/browse/AUT-773

id attributes get translated

Pre-requisite: To have an item created.

SETPS to test:
• Checkout to branch: fix/AUT-773/id-attributes-get-translated
• change the language
• go inside an item authoring
• Group name on the left should be on the selected language ( common interactions, inline interactions, graphic interactions, custom interactions.)
• All interactions should be displayed correctly
• Inspect elements in the  dev tools: Group id shouldn't change independently of the language

Actual result: <section id are different depending on language
![image](https://user-images.githubusercontent.com/60346520/135067173-2ad3a34d-2b25-42f5-a344-50884fdf3c1c.png)

Expected result: section id's are always in English independently of the language that the item is set in
![image](https://user-images.githubusercontent.com/60346520/135066480-0c9ce42a-d62b-4ab0-b4f6-d1b4c4182652.png)

Testing env: http://test-silvia.playground.kitchen.it.taocloud.org:41441/

2021-09-28 13:27 UTC, AnastasiaArcadia approved these changes
- [x] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not master

2021-09-29 07:24 UTC, Silvia-loza commented on views/js/portableElementRegistry/factory/ciRegistry.js
> +                        group : 'custom-interaction'
you're right, missing an 's'  will correct  now  :)

2021-09-29 09:46 UTC, adriloma approved these changes
Works good, but is there any reason to use `let` instead of `const` as a default? Seems every new `let` declaration could be declared as a constant instead, as they are never modified.

- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [x] Commits are following conventional commits
- [x] Commits messages are meaningful
- [x] Commits are atomic

2021-09-29 14:55 UTC, bziondik requested changes
Use `let` only if needed
change  `groupName` to `groupId`

2021-09-29 14:55 UTC, bziondik commented on views/js/qtiCreator/editor/interactionsToolbar.js
> +    function getGroupId(groupName){
Can we use `groupId` instead `groupName`? It is more clear

2021-10-01 08:27 UTC, bziondik approved these changes
- [ ]  New code is covered by tests (if applicable)
- [x]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [x]  New code is not subject to concurrency issues (if applicable)
- [x]  Feature is working correctly on my local machine (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request title and description are meaningful

2021-10-04 13:26 UTC, merged