Feature/aut 1195/e2e add asset passage to interaction
oat-sa/extension-tao-itemqti pull request #1960
Opened 2021-11-26 16:43 UTC by Silvia-loza

**End to end testing.**
Related to: https://oat-sa.atlassian.net/browse/AUT-1195
Depends on :
oat-sa/tao-mediamanager#359

Description of changes:
Support functions (resource manager) for handling e2e tests for: Creating and importing passages/asset and adding to prompt and choice of interaction

How to run locally:
Checkout to branch `feature/AUT-1195/e2e-add-asset-passage-to-interaction`
in extensions:
- https://github.com/oat-sa/tao-core
- https://github.com/oat-sa/extension-tao-itemqti
- https://github.com/oat-sa/extension-tao-mediamanager

**run tests from tao core extn:*
npm run cy:open - to run in browser
or npm run cy:run - for headless execution
File to test: add-asset-passage-to-interaction.spec.js
**All tests should pass:**
![image](https://user-images.githubusercontent.com/60346520/143610903-80488e09-8602-44a6-a1dc-55f1ef21a3ab.png)

2021-12-01 12:52 UTC, adriloma approved these changes
- [x] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [x] Commits are following conventional commits
- [x] Commits messages are meaningful
- [x] Commits are atomic

2021-12-02 07:58 UTC, bziondik requested changes

2021-12-02 07:58 UTC, bziondik commented on views/cypress/utils/resource-manager.js
> +export function selectUploadSharedStimulus(isCreatedAsset) {
This is related to taoMediaManager should be put in https://github.com/oat-sa/extension-tao-mediamanager/blob/master/views/cypress/utils/resource-manager.js
taoQtiItem can be used without taoMediaManager

2021-12-02 07:58 UTC, bziondik commented on views/cypress/utils/resource-manager.js
> +            cy.getSettled(`.file-selector .files [data-alt="passage NEW.xml"]`).should('exist');
better to set name as param

2021-12-03 12:32 UTC, bziondik approved these changes
- [ ]  New code is covered by tests (if applicable)
- [ ]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [x]  New code is not subject to concurrency issues (if applicable)
- [x]  Feature is working correctly on my local machine (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request title and description are meaningful
![image](https://user-images.githubusercontent.com/25976342/144603153-6da7c6cc-2668-4fcd-bb63-10d8063c3774.png)

2021-12-03 16:12 UTC, merged