fix: failing to save A block with table when adding scroll
oat-sa/extension-tao-itemqti pull request #1989
Opened 2022-01-05 11:12 UTC by Silvia-loza

Related to Issue: https://oat-sa.atlassian.net/browse/AUT-726

**A-block with table inside no saving when enabling scrolling.**
pre-requisites: create an item with and A block inside 

**SETPS to test:**
• Checkout to branch: fix/AUT-726/A-block-with-table-fail-when-adding-scroll
• Go into the authoring of the Item created
•add a table inside and save

**ACTUAL RESULT:**
Unable to save. error on the level of Qti model

**EXPECTED RESULT:**
A block with table and scroll enabled saves correctly.

![image](https://user-images.githubusercontent.com/60346520/148208212-fd3ebbba-e37f-466e-ac0a-a62a0b7ad44d.png)

ENV to test: TBC

2022-01-06 08:49 UTC, bziondik requested changes
Issue in `.find('[data-html-editable]')` - it returns table also, you need child

2022-01-06 08:49 UTC, bziondik commented on views/js/qtiCreator/widgets/static/helpers/itemScrollingMethods.js
> +                    ? widget.$container.find('[data-html-editable]').first(`.${wrapperTextCls}`)
```suggestion
                    ? widget.$container.children('[data-html-editable]').first(`.${wrapperTextCls}`)
```

2022-01-06 08:49 UTC, bziondik commented on views/js/qtiCreator/widgets/static/helpers/itemScrollingMethods.js
> +                    ? widget.$container.find('[data-html-editable]').first(`.${wrapperTextCls}`)
and also line 84 
find('[data-html-editable]') => .children('[data-html-editable]')

2022-01-10 08:51 UTC, bziondik approved these changes
- [ ]  New code is covered by tests (if applicable)
- [ ]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [x]  New code is not subject to concurrency issues (if applicable)
- [x]  Feature is working correctly on my local machine (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request title and description are meaningful

2022-01-10 09:20 UTC, meefox approved these changes
Item saved
<img width="1023" alt="Screenshot 2022-01-10 at 10 18 27" src="https://user-images.githubusercontent.com/2067027/148742765-94881e55-8b15-48c7-b41b-d2355a1dd727.png">

well done

- [ ] New code is covered by tests
- [ ] Tests are running successfully (old and new ones) on my local machine
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

2022-01-11 07:17 UTC, AntonNeviarouski commented
QA verified

2022-01-11 09:17 UTC, merged