fix: add clearfix to position image inside canvas
oat-sa/extension-tao-itemqti pull request #2003
Opened 2022-01-20 15:40 UTC by Silvia-loza

Related to Issue: https://oat-sa.atlassian.net/browse/AUT-1667

Wrap text around image - image is positioned outside of A-block
**pre-requisites:** 
**Enable text-wrap** =>  mediaAlignment plugin.:
set in config/tao/client_lib_config_registry.conf.php configs

 ```
       'ui/image/ImgStateActive' => array(
            'mediaAlignment' => true
        ),
```
**Enable Multi column** =>
config/taoQtiItem/qtiCreator.conf.php
`‘multi-column’ => true, `

Create an item, and test with preview in solar.
Publish a local delivery with preview in terre.

**SETPS to test:**
• Checkout to branch: fix/AUT-1667/wrap-text-img-positioned-outside-A-block (**also in tao-core-ui.fe & tao-deliver-fe**)
• Create an item, add an A block and put an image inside it.
• Click in image go to the right panel and click in size and position changing the alignment. 
• Add more blocks with the + sign and put images in them.
•Check that the image is still inside the canvas (doesn't overflow)
•Save and Preview the item. (solar UI config) images and text should be as authored.
•Publish a delivery in local: sign in as test taker,  items should be displayed with alignment as authored

**ACTUAL RESULT:**
in item authoring and shared stimulus authoring, image overflows outside the container when text wrap is used.
In New UI and Terre delivery view alignment is not correct.

**EXPECTED RESULT:**
item and shared stimuluss authroing image is within the container.
Items are viewed with alignement as authored in terre and solar delivery

2022-01-24 12:16 UTC, bziondik requested changes

2022-01-24 12:16 UTC, bziondik commented on views/scss/qtiCreator/_grid-editor.scss
> +    &:before {
https://github.com/oat-sa/tao-core-ui-fe/blob/ab598265609cd90ee148c7bf2e2a0732e13e2ad3/scss/inc/_variables.scss#L13-L21
before and after already included in extend `%clearfix`

2022-01-25 10:01 UTC, clagosarias approved these changes
Code review only
- [ ] New code is covered by tests (if applicable)
- [ ]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [ ]  New code is not subject to concurrency issues (if applicable)
- [ ]  The feature is working correctly on my local machine (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request's target is not master

2022-01-28 07:48 UTC, bziondik approved these changes
- [ ]  New code is covered by tests (if applicable)
- [x]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [x]  New code is not subject to concurrency issues (if applicable)
- [x]  Feature is working correctly on my local machine (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request title and description are meaningful

2022-01-31 17:22 UTC, merged