Feature/aut 120/support parsing figcaption element
oat-sa/extension-tao-itemqti pull request #2138
Opened 2022-05-25 16:11 UTC by pnal

2022-06-02 05:42 UTC, marpesia requested changes
On Kitchen and Local environments, if I save the files, I have this error on the console. The file is saved correctly. I've tried with several images to check.
![image](https://user-images.githubusercontent.com/11692751/171560740-4d3a1c16-da6e-4c09-ae75-1ddf82469def.png)

Update on the kitchen:
Now I can't save the Item
![image](https://user-images.githubusercontent.com/11692751/171583330-481174c8-ecba-404d-8267-6d32856c36a8.png)

2022-06-08 06:57 UTC, marpesia requested changes
On Items and Assets
All AC are met ✅ 
Issue:
- After adding an image with a caption, I got several errors on clicking out of the Image and clicking on the A Block.
![image](https://user-images.githubusercontent.com/11692751/172547445-9f486a7b-3da4-450e-a178-eae6e304bd72.png)
- On adding an Asset to an Item, the font size change affects the Item AND the Asset
![image](https://user-images.githubusercontent.com/11692751/172551603-8d543966-b7a1-4a51-b517-99f16028ea92.png)

2022-06-08 13:20 UTC, marpesia approved these changes
Awesome!

**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful
- [ ] Pull request's target is not `master`
- [ ] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] Commits messages are meaningful
- [ ] Commits are atomic
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

2022-06-08 16:07 UTC, Silvia-loza approved these changes
It works well and looks very good.  
Responsiveness from typing text till you see it in figcaption is super fast as well. Great job!   :clap: :clap:
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [X] New code is respecting code style rules
- [X] New code is respecting best practices
- [X]  Pull request's target is not` master`
- [X] Feature is working correctly on my local machine (if applicable)
- [X] Acceptance criteria are respected
- [X] Pull request title and description are meaningful

2022-06-10 10:31 UTC, andreluizmachado requested changes

2022-06-10 10:31 UTC, andreluizmachado commented on model/qti/container/ContainerGap.php
> +            \oat\taoQtiItem\model\qti\Figure::class,
can we use `{classname}::class` in all of them?
please check the other classes that you touched as well

2022-06-10 10:31 UTC, andreluizmachado commented on model/qti/container/ContainerFigure.php
> +    public function getValidElementTypes()
can we use a return type hint?

2022-06-10 10:31 UTC, andreluizmachado commented on model/qti/ParserFactory.php
> +    protected function getHTML5Namespace()
can we use return type hint?

2022-06-10 10:31 UTC, andreluizmachado commented on model/qti/ParserFactory.php
> +    private function buildFigCaption(DOMElement $data)
can we use return type hint?

2022-06-10 10:31 UTC, andreluizmachado commented on model/qti/ParserFactory.php
> +    private function buildFigure(DOMElement $data)
same here

2022-06-13 06:47 UTC, andreluizmachado approved these changes
- [x] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

2022-06-13 08:27 UTC, merged