Fix/aut 1906/allow score maxscore
oat-sa/extension-tao-itemqti pull request #2191
Opened 2022-07-29 16:48 UTC by shaveko

related to https://oat-sa.atlassian.net/browse/AUT-1906

### Description
When response processing is turned off for interaction, SCORE and MAXSCORE outcome declarations are ignored and not saved into item xml, this PR allows them to be entered manually and saved

### How to test

- run unit tests
- check with related PR (https://github.com/oat-sa/tao-item-runner-qti-fe/pull/308)

2022-08-02 16:40 UTC, bziondik requested changes
From ticket, as I understand user will use property External Scored
<img width="187" alt="image" src="https://user-images.githubusercontent.com/25976342/182427759-7b54a884-2428-4266-ac4f-6de2d3cae208.png">
let's now add to removing condition this property - if it is none, then all should works as it is
but if it Human or External Machine, then we don't remove this outcome

2022-08-04 08:23 UTC, shaveko commented
> if it is none, then all should works as it is
> but if it Human or External Machine, then we don't remove this outcome

Thanks, I've implemented the check in `-fe` lib

2022-08-04 12:17 UTC, bziondik requested changes
I found regression
steps to reproduce kitchen env_local dev env:
create item
add choice interaction
set its response processing to none
save and check payload - it equal
add one move choice interaction
save, check payload
for your branch `SCORE` is present
![image](https://user-images.githubusercontent.com/25976342/182844670-15e370e9-eb03-46f0-b98d-8e92185e2348.png)
<img width="1390" alt="image" src="https://user-images.githubusercontent.com/25976342/182844722-62f89299-2b1b-4cc6-bb43-0bc06224d74c.png">

2022-08-04 12:17 UTC, bziondik commented on views/js/qtiCreator/widgets/interactions/states/NoRp.js
> -        if(!rpXml.trim()){
maybe we need also check here instead removing? 
```
maxScoreOutcome = item.getOutcomeDeclaration('MAXSCORE');
if(!(maxScoreOutcome.attributes && maxScoreOutcome.attributes.externalScored)) {
   item.removeOutcome('MAXSCORE');
```

2022-08-04 12:32 UTC, bziondik approved these changes
- [ ]  New code is covered by tests (if applicable)
- [x]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [x]  New code is not subject to concurrency issues (if applicable)
- [x]  Feature is working correctly on my local machine (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request title and description are meaningful
![image](https://user-images.githubusercontent.com/25976342/182847107-a183ec07-f231-41cd-a62a-c956dad8a1f1.png)
<img width="638" alt="image" src="https://user-images.githubusercontent.com/25976342/182847595-409b9f8d-8ce4-47bd-86f9-a33204311c13.png">

2022-08-04 14:43 UTC, meefox approved these changes
**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [x] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] Commits messages are meaningful
- [x] Commits are atomic
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

2022-08-12 13:11 UTC, merged