fix: catch not found exception
oat-sa/extension-tao-itemqti pull request #2262
Opened 2022-11-09 16:10 UTC by pnal

[AUT-2774](https://oat-sa.atlassian.net/browse/AUT-2774)

2022-11-09 16:25 UTC, andreluizmachado commented on model/portableElement/storage/PortableElementRegistry.php
> +            return null;
Can we log it at least?

2022-11-09 16:26 UTC, andreluizmachado commented on model/portableElement/storage/PortableElementRegistry.php
> +            return null;
Can we have unit tests?

2022-11-09 17:18 UTC, bartlomiejmarszal requested changes
Should we log error when catching this exception?

2022-11-10 14:06 UTC, bartlomiejmarszal approved these changes

2022-11-10 15:44 UTC, andreluizmachado approved these changes
- [x] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [ ] Changelog is updated according to changes (if applicable)
- [ ] Documentation is updated according to changes (if applicable)

2022-11-10 15:51 UTC, merged