fix: fix overflow bug
oat-sa/extension-tao-itemqti pull request #2334
Opened 2023-03-30 12:48 UTC by rgomeztao

coming from [AUT-3027](https://oat-sa.atlassian.net/browse/AUT-3027)

changelog:
* fixes overflow on associate interaction

2023-04-04 06:50 UTC, jsconan requested changes
The issue described in the ticket is fixed.
However, it also introduces another issue as a choice with content that fits the container cannot be dragged and dropped in any box.

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/1500098/229710065-f3e4c86d-9e96-4672-8536-344f8877560d.png">

<video src="https://user-images.githubusercontent.com/1500098/229710666-5a7227dd-544d-454b-ac9a-efdc561af63c.mp4"></video>

Regarding the PR itself, I also see 2 things that are not correct:
- the base branch should be `develop` not `master`, unless it is a release branch.
- the branch name does not reflect the intent: I don't think it is a feature as it is rather a fix

2023-04-04 06:56 UTC, jsconan commented on views/scss/qti/_associate.scss
> -            max-width: 180px;
Quick fix :)
But I wonder if it is not too aggressive, see my previous comment.

BTW, this line has not changed for 7y, the last change is from https://github.com/oat-sa/extension-tao-itemqti/commit/978c2f165e83e8f2e285df879a1c453402719234#diff-f2f402bcd0bcb674fae83ec4cd965a7c21527cb011203c050271d161c2a42ab6L21

2023-04-06 08:32 UTC, jsconan reviewed
It works, but it looks a bit odd. Maybe should we add a word-wrap?
![image](https://user-images.githubusercontent.com/1500098/230320558-e648138e-0ed0-4608-8d83-14344333d635.png)

BTW, I don't see the rule for the choices having a Maths expression

2023-04-10 06:57 UTC, rgomeztao commented
added word wrap for long text strings :)

you can find the selector for the math expressions here
![image](https://user-images.githubusercontent.com/118912884/230845455-0f4c7e55-4387-44e4-921b-8e9eb80db586.png)

thanks! :)

2023-04-11 09:28 UTC, jsconan approved these changes
The issue is fixed. Nice job!

![image](https://user-images.githubusercontent.com/1500098/231116915-94a51c73-bc81-4489-b5d5-c9d221079796.png)

**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code respects code style rules
- [x] New code respects best practices
- [ ] ~~New code is not subject to concurrency issues (if applicable)~~
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`
- [x] Commits are following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] Commits messages are meaningful
- [x] Commits are atomic

2023-04-11 10:59 UTC, jsconan approved these changes

2023-04-11 14:42 UTC, merged