Feat/aut 3590 add metadata check on import
oat-sa/extension-tao-itemqti pull request #2481
Opened 2024-04-11 09:38 UTC by Karol-Stelmaczonek

Ticket: https://oat-sa.atlassian.net/browse/AUT-3590

## What's Changed

- Add metametadata check & validation on import

## Dependencies PRs

- https://github.com/oat-sa/extension-tao-testqti/pull/2452
- https://github.com/oat-sa/extension-tao-testqti/pull/2454

## How to test
- Create import with metadata
- Run import
- If import class don't have proper metadata the import will fail

2024-04-12 08:16 UTC, bartlomiejmarszal commented on model/qti/ImportService.php
> +
Why do you need this?

2024-04-12 08:16 UTC, bartlomiejmarszal commented on model/qti/ImportService.php
> +
More! More empty lines!

2024-04-12 08:21 UTC, bartlomiejmarszal commented on model/qti/metaMetadata/Exception.php
> +class Exception extends \common_Exception
Can we rename it?

2024-04-12 08:22 UTC, bartlomiejmarszal commented on model/qti/metaMetadata/Exception.php
> +class Exception extends \common_Exception
Move exception to use block
```suggestion
class Exception extends common_Exception
```

2024-04-12 08:23 UTC, bartlomiejmarszal commented on model/qti/metaMetadata/Exception.php
> +
More! More empty lines!
```suggestion

```

2024-04-12 08:36 UTC, bartlomiejmarszal commented on model/qti/metaMetadata/Exporter.php
> +class Exporter extends ConfigurableService
[And if you need to build a second floor. You have a door already](https://www.youtube.com/watch?v=Uouj0eAxRc0)!

2024-04-12 08:39 UTC, bartlomiejmarszal commented on model/qti/metaMetadata/Importer.php
> +        $properties  = $xpath->query('//imsmd:metaMetadata/default:extension/default:customProperties/default:property');
Maybe we can move it to const?

2024-04-12 08:40 UTC, bartlomiejmarszal commented on model/qti/metaMetadata/Importer.php
> +class Importer extends ConfigurableService
Can we change this name?

2024-04-12 08:43 UTC, bartlomiejmarszal commented on model/qti/metaMetadata/MetaMetadataService.php
> +    public const SERVICE_ID = 'taoQtiItem/metaMetadataService';
You can use `::class` when registering services
```suggestion
```

2024-04-12 08:46 UTC, bartlomiejmarszal commented on model/qti/metaMetadata/MetaMetadataService.php
> +class MetaMetadataService extends ConfigurableService
Why do you need this class?

2024-04-12 13:04 UTC, bartlomiejmarszal requested changes
We should have a better control over metadata validation. I expect in future to not fail import when metadata fields are not matching. We could also import resources without metadata or import resources in class with metadata.

2024-04-12 13:04 UTC, bartlomiejmarszal commented on model/qti/ImportService.php
> +    }
Extract this to new service

2024-04-12 13:10 UTC, bartlomiejmarszal requested changes
We should validate all metadata nested from all parents

2024-04-12 13:10 UTC, bartlomiejmarszal commented on model/qti/ImportService.php
> +        $props = $itemClass->getProperties();
Isn't this class a new class always so it will never has property values?

2024-04-12 13:17 UTC, bartlomiejmarszal requested changes
Can we have more control over metadata objects that we want to inject into resource?

2024-04-12 13:17 UTC, bartlomiejmarszal commented on model/qti/ImportService.php
> +        $metaMedataValues = []
You are taking all metadata from all package into `importQtiItem`. 
`importQtiItem` is importing particular item, no?

2024-04-17 15:24 UTC, bartlomiejmarszal commented on model/qti/metadata/imsManifest/MetaMetadataValidator.php
> +            if (count($foundMetadata) > 1) {
If we don't find metadata corresponding to class properties we should not throw error.

2024-04-23 07:49 UTC, tikhanovichA approved these changes
- [x] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

2024-04-23 08:32 UTC, pnal approved these changes
Good job!
- [x] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

2024-04-23 08:32 UTC, pnal commented on model/qti/metadata/imsManifest/MetaMetadataExtractor.php
> +    // phpcs:disable Generic.Files.LineLength
you can probably break it in two lines instead, I guess it's valid

2024-04-23 08:32 UTC, pnal commented on model/qti/metadata/imsManifest/MetaMetadataExtractor.php
> +    private const META_METADATA_PROPERTIES_QUERY_STRING = '//imsmd:metaMetadata/default:extension/default:customProperties/default:property';
AFAIK breaking it in two lines would also be legit
```suggestion
    private const META_METADATA_PROPERTIES_QUERY_STRING =
    '//imsmd:metaMetadata/default:extension/default:customProperties/default:property';
```

2024-05-07 13:43 UTC, merged